"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.3.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = False  # Set to True during development

ALLOWED_HOSTS = ['yourdomain.com', 'localhost', '127.0.0.1', 'your-vercel-url.vercel.app']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'alumni_forum_db',
        'USER': 'postgres',
        'PASSWORD': 'Goutham@123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # For handling CORS requests
]

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # For handling cross-origin requests
]

CORS_ALLOWED_ORIGINS = [
    "https://yourdomain.com",
    "https://your-vercel-url.vercel.app",
]
